# Generated by Django 3.0.4 on 2020-03-06 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pisma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peganode',
            name='login',
        ),
        migrations.RemoveField(
            model_name='peganode',
            name='password',
        ),
        migrations.AddField(
            model_name='peganode',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
