# Generated by Django 3.0.4 on 2020-03-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pisma', '0002_auto_20200306_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peganode',
            name='user',
        ),
        migrations.AddField(
            model_name='peganode',
            name='login',
            field=models.CharField(default='PegaAPI_Tech', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peganode',
            name='password',
            field=models.CharField(default='rules', max_length=200),
            preserve_default=False,
        ),
    ]
